ALTER TABLE flights ADD COLUMN IF NOT EXISTS vertical_rate DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE flights ADD COLUMN IF NOT EXISTS geo_altitude DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE flights ADD COLUMN IF NOT EXISTS squawk TEXT NOT NULL DEFAULT '';
ALTER TABLE flights ADD COLUMN IF NOT EXISTS category SMALLINT NOT NULL DEFAULT 0;
